fastcgi_cache_path /etc/nginx/cache/???USER??? levels=1:2 keys_zone=???USER???:10m max_size=10g inactive=60m use_temp_path=off;

server {

    listen 80;
    listen [::]:80;

    server_tokens off;

    server_name ???DOMAIN??? www.???DOMAIN???;

    root ???BASE???;

    client_body_timeout 10s;
    client_header_timeout 10s;
    client_max_body_size 256M;

    add_header X-XSS-Protection "1; mode=block";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    access_log /home/???USER???/log/access.log;
    error_log /home/???USER???/log/error.log;

    index index.html index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }
    
    location = /robots.txt  { 
        access_log off; 
        log_not_found off; 
    }

    error_page 404 /index.php;

    gzip             on;
    gzip_comp_level  2;
    gzip_min_length  1000;
    gzip_proxied     expired no-cache no-store private auth;
    gzip_types       text/plain application/x-javascript text/xml text/css application/xml;

    location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
    }

    set $skip_cache 0;

    if ($request_method = POST) {
        set $skip_cache 1;
    }
    
    if ($query_string != "") {
        set $skip_cache 1;
    }

    if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|index.php|/.*sitemap.*\.(xml|xsl)") {
        set $skip_cache 1;
    }

    if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
        set $skip_cache 1;
    }

    location ~ /xmlrpc.php {
        limit_req zone=login_limit burst=2 nodelay;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php???PHP???-fpm-???USER???.sock;
    }

    location ~ /wp-login.php {
        limit_req zone=login_limit burst=2 nodelay;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php???PHP???-fpm-???USER???.sock;
    }

    include snippets/wp-security.conf;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php???PHP???-fpm-???USER???.sock;
        fastcgi_cache ???USER???;
        fastcgi_cache_valid 200 301 302 1h;
        fastcgi_cache_use_stale error timeout updating invalid_header http_500 http_503;
        fastcgi_cache_min_uses 1;
        fastcgi_cache_lock on;
        fastcgi_cache_bypass $skip_cache;
        fastcgi_no_cache $skip_cache;
        add_header X-FastCGI-Cache $upstream_cache_status;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

}